In [6]:
import pandas as pd
import os

In [2]:
patients = pd.read_csv("../../..//data/mimic-4/patients.csv")

In [3]:
patients.shape

(364627, 6)

In [4]:
patients.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10000032      F          52         2180       2014 - 2016  2180-09-09
1    10000048      F          23         2126       2008 - 2010         NaN
2    10000058      F          33         2168       2020 - 2022         NaN
3    10000068      F          19         2160       2008 - 2010         NaN
4    10000084      M          72         2160       2017 - 2019  2161-02-13

In [15]:
patients.dtypes

subject_id            int64
gender               object
anchor_age            int64
anchor_year           int64
anchor_year_group    object
dod                  object
birth_year            int64
dtype: object

In [14]:
patients["birth_year"] = patients["anchor_year"] - patients["anchor_age"]

In [9]:
trajectories = pd.read_csv('trajectories.csv').drop(columns=['Unnamed: 0'])
trajectories.shape

(5938215, 8)

In [10]:
trajectories.head()

,subject_id,hadm_id,seq_num,icd10_code,icd10_category,admittime,dischtime,deathtime
0,10000032,22595853,1,K766,K76,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN
1,10000032,22595853,2,R188,R18,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN
2,10000032,22595853,3,K740,K74,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN
3,10000032,22595853,4,B1920,B19,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN
4,10000032,22595853,5,J449,J44,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN

In [16]:
trajectories_patients = pd.merge(
    how="left",
    on="subject_id",
    left=trajectories,
    right=patients[["subject_id", "gender", "birth_year", "dod"]]
)

In [18]:
trajectories_patients.count()

subject_id        5938215
hadm_id           5938215
seq_num           5938215
icd10_code        5938215
icd10_category    5938215
admittime         5938215
dischtime         5938215
deathtime          238549
gender            5938215
birth_year        5938215
dod               2149226
dtype: int64

In [19]:
trajectories_patients.to_csv("trajectories.csv", index=False)